import { apiClient, IS_MOCK } from "@/lib/apiClient"
import { mockCandidates } from "@/lib/mockData"

const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms))

const candidateProfile = {
  id: "1",
  firstName: "Sachin",
  lastName: "Verma",
  title: "Senior Software Engineer",
  email: "sachin@example.com",
  phone: "+1 234 567 890",
  location: "San Francisco, CA",
  completionScore: 85,
  skills: ["React", "Next.js", "TypeScript", "Node.js", "Tailwind CSS"],
  experience: [
    {
      id: "exp1",
      role: "Software Engineer",
      company: "Tech Corp",
      start: "2021",
      end: "Present",
      description: "Building awesome web applications.",
    },
  ],
  education: [
    {
      id: "edu1",
      degree: "B.Tech in Computer Science",
      institution: "IIT Bombay",
      year: "2020",
    },
  ],
  links: {
    github: "https://github.com/sachin",
    linkedin: "https://linkedin.com/in/sachin",
    portfolio: "https://sachin.dev",
  },
}

/** Helper: trigger a file download in the browser from a Blob */
function triggerBrowserDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/** Helper: build a plain-text blob from a candidate profile object */
function buildProfileText(candidate: any): string {
  const lines = [
    "CANDIDATE PROFILE",
    "=================",
    `Name: ${candidate.name}`,
    `Role Applied: ${candidate.role}`,
    `Status: ${candidate.status}`,
    `Applied Date: ${new Date(candidate.appliedDate).toLocaleDateString()}`,
    `Experience: ${candidate.experience}`,
    `Match Score: ${candidate.matchScore}%`,
    "",
    "Generated by HireLoop ATS",
    `Downloaded: ${new Date().toLocaleString()}`,
  ]
  return lines.join("\n")
}

export const candidateService = {
  getProfile: async () => {
    if (IS_MOCK) {
      await delay(500)
      return candidateProfile
    }
    return apiClient.get<any>("/candidates/me")
  },

  updateProfile: async (data: any) => {
    if (IS_MOCK) {
      await delay(600)
      return { ...candidateProfile, ...data }
    }
    return apiClient.put<any>("/candidates/me", data)
  },

  getAllCandidates: async () => {
    if (IS_MOCK) {
      await delay(500)
      return mockCandidates
    }
    return apiClient.get<any[]>("/candidates")
  },

  getCandidateById: async (id: string) => {
    if (IS_MOCK) {
      await delay(300)
      return mockCandidates.find(c => c.id === id)
    }
    return apiClient.get<any>(`/candidates/${id}`)
  },

  /**
   * Download the candidate's uploaded resume.
   * In production, the backend returns a signed URL or binary stream.
   */
  downloadResume: async (candidateId: string, candidateName: string) => {
    if (IS_MOCK) {
      await delay(1200)
      const content = `RESUME\n======\n${candidateName}\n\nThis is a mock resume preview.\nIn production, the actual uploaded PDF/DOCX will be downloaded.`
      const blob = new Blob([content], { type: "text/plain" })
      const filename = `${candidateName.replace(/\s+/g, "_")}_Resume.txt`
      triggerBrowserDownload(blob, filename)
      return { success: true }
    }
    const response = await apiClient.get<Blob>(`/candidates/${candidateId}/resume/download`, { responseType: "blob" } as any)
    const blob = new Blob([response as any])
    triggerBrowserDownload(blob, `${candidateName.replace(/\s+/g, "_")}_Resume.pdf`)
    return { success: true }
  },

  /**
   * Download a structured candidate profile as a text/JSON file.
   * In production this would return a formatted PDF from the backend.
   */
  downloadCandidateProfile: async (candidateId: string, candidate: any) => {
    if (IS_MOCK) {
      await delay(900)
      const text = buildProfileText(candidate)
      const blob = new Blob([text], { type: "text/plain" })
      const filename = `${candidate.name.replace(/\s+/g, "_")}_Profile.txt`
      triggerBrowserDownload(blob, filename)
      return { success: true }
    }
    const response = await apiClient.get<Blob>(`/candidates/${candidateId}/profile/download`, { responseType: "blob" } as any)
    const blob = new Blob([response as any])
    triggerBrowserDownload(blob, `${candidate.name.replace(/\s+/g, "_")}_Profile.pdf`)
    return { success: true }
  },

  /**
   * Download the complete candidate package (resume + profile + documents).
   * In production the backend generates and returns a ZIP archive.
   */
  downloadCandidatePackage: async (candidateId: string, candidateName: string) => {
    if (IS_MOCK) {
      await delay(2000)
      const content = `COMPLETE CANDIDATE PACKAGE\n==========================\n${candidateName}\n\nThis package would contain:\n- Resume (PDF/DOCX)\n- Candidate Profile\n- Uploaded Documents\n\nGenerated by HireLoop ATS\nDownloaded: ${new Date().toLocaleString()}`
      const blob = new Blob([content], { type: "text/plain" })
      const filename = `${candidateName.replace(/\s+/g, "_")}_Complete_Package.txt`
      triggerBrowserDownload(blob, filename)
      return { success: true }
    }
    const response = await apiClient.get<Blob>(`/candidates/${candidateId}/package/download`, { responseType: "blob" } as any)
    const blob = new Blob([response as any])
    triggerBrowserDownload(blob, `${candidateName.replace(/\s+/g, "_")}_Package.zip`)
    return { success: true }
  },
}

