const ACTIVITY_ACTIONS = Object.freeze({
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  JOB_CREATED: 'JOB_CREATED',
  JOB_UPDATED: 'JOB_UPDATED',
  JOB_CLOSED: 'JOB_CLOSED',
  JOB_DELETED: 'JOB_DELETED',
  APPLICATION_CREATED: 'APPLICATION_CREATED',
  APPLICATION_STATUS_CHANGED: 'APPLICATION_STATUS_CHANGED',
  ASSESSMENT_ASSIGNED: 'ASSESSMENT_ASSIGNED',
  ASSESSMENT_SUBMITTED: 'ASSESSMENT_SUBMITTED',
  AI_INTERVIEW_COMPLETED: 'AI_INTERVIEW_COMPLETED',
  OFFER_CREATED: 'OFFER_CREATED',
  EMPLOYER_FINAL_DECISION: 'EMPLOYER_FINAL_DECISION',
  RESUME_UPLOADED: 'RESUME_UPLOADED',
  RESUME_DELETED: 'RESUME_DELETED',
});

module.exports = { ACTIVITY_ACTIONS };
