const NOTIFICATION_TYPE = Object.freeze({
  APPLICATION_STATUS_CHANGED: 'APPLICATION_STATUS_CHANGED',
  ASSESSMENT_ASSIGNED: 'ASSESSMENT_ASSIGNED',
  AI_INTERVIEW_READY: 'AI_INTERVIEW_READY',
  OFFER_RECEIVED: 'OFFER_RECEIVED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',
  NEW_APPLICANT: 'NEW_APPLICANT',
  GENERAL: 'GENERAL',
});

module.exports = {
  NOTIFICATION_TYPE,
  ALL_NOTIFICATION_TYPES: Object.values(NOTIFICATION_TYPE),
};
